In [ ]:
import numpy as np

# 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1)

# 2D NumPy array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("\n2D Array:")
print(arr2)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]


1.to create a numpy array with an example

In [ ]:
import numpy as np

# 1D array
a = np.array([10, 20, 30])
print("Array a:", a)
print("ndim of a:", a.ndim)

# 2D array
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("\nArray b:")
print(b)
print("ndim of b:", b.ndim)

# 3D array
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])
print("\nArray c:")
print(c)
print("ndim of c:", c.ndim)

Array a: [10 20 30]
ndim of a: 1

Array b:
[[1 2 3]
 [4 5 6]]
ndim of b: 2

Array c:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim of c: 3


2.what is ndim in npy with an example

ans
 ndim in NumPy tells you how many dimensions (axes) an array has.

Simple meaning

1D array → ndim = 1

2D array → ndim = 2

3D array → ndim = 3

In [ ]:
import numpy as np

arr = np.arange(12, 15, 3)
print(arr)


[12]


3.To generate a value of arrays from range from 12-15 with a step value of 3

In [ ]:
import numpy as np

# Create values from 15 to 30
arr = np.arange(15, 31)

# Reshape into a 2D array (4 rows, 4 columns)
arr_2d = arr.reshape(4, 4)

print("2D Array:")
print(arr_2d)

print("\nShape of the array:", arr_2d.shape)
print("Size of the array:", arr_2d.size)


2D Array:
[[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]

Shape of the array: (4, 4)
Size of the array: 16


4.explain the shape of 2d array and the size with example ,reshape the value to [15,16................30]

In [ ]:
import numpy as np

# Create values from 15 to 30
arr = np.arange(15, 31)

# Reshape into a 2D array (4 rows, 4 columns)
arr_2d = arr.reshape(4, 4)

print("2D Array:")
print(arr_2d)

print("\nShape of the array:", arr_2d.shape)
print("Size of the array:", arr_2d.size)


2D Array:
[[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]

Shape of the array: (4, 4)
Size of the array: 16


5.explain the shape of 2d array and the size with example ,reshape the value to [15,16................30]

6.difference btwn np.md and np.0

ans

np.ndim -
Tells how many dimensions (axes) an array has.
It explains the structure of the array (1D, 2D, 3D, etc.).

np.size -
Tells the total number of elements present in the array.
It explains how many values are stored in the array.

7.Difference between np.eye and np.identity

ans

np.eye
Creates a matrix with 1s on the diagonal and 0s elsewhere.
It is more flexible because it can create square or rectangular matrices.

np.identity
Creates a square identity matrix only, with 1s on the main diagonal and 0s elsewhere.
It is simple and fixed in size.